angular.module('injectModules',[
	'ui.router',
	'ui.sortable',
	// 'ui.bootstrap',
	'ui.calendar',
	// 'ngAnimate',
	// 'ngResource',
	'searchByTextModule',
	'headerModule',
	'leftNavModule',
	'constModule',
	'utilFactoryModule',
	'smsCodeModule',
	'breadcrumbModule',
	'checkControllerModule',
	'gobackModule',
	'tableComponentModule',
	'paginationModule',
	'hasPermisstionComponent',
	'getRefreshTokenFacotryModule',
	'localStorageFactoryModule',
	'loginHttpServiceModule',
	'loginControllerModule',
	'forgetControllerModule',
	'cloudDataControllerModule',
	'activeControllerModule',
	
	'adminControllerModule',
	'masterLoginControllerModule',
	'masterControllerModule',
	'masterAddControllerModule',
	'masterDetailControllerModule',
	'applicationAdminHttpServiceModule',
	'passengerControllerModule',
	'passengerHttpServiceModule',
	'passengerAddControllerModule',
	'passengerDetailControllerModule',
	'listControllerModule',
	'reportControllerModule',
	'feedbackControllerModule',
	
	'schedulerControllerModule',
	'schedulerHttpServiceModule',
	'schedulerDriverControllerModule',
	'schedulerDriverDetailControllerModule',
	'schedulerAddDriverControllerModule',
	'schedulerCalendarControllerModule',
	'schedulerAddScheduleControllerModule',
	'schedulerBusControllerModule',
	'schedulerSiteControllerModule',
	'schedulerUpdateSiteControllerModule',
	'schedulerbusCompanyControllerModule',
	
	'schedulerAddBusControllerModule',
	'schedulerBusDetailControllerModule',
	
	'schedulerAddSiteControllerModule',
	
	'schedulerRouteControllerModule',
	'schedulerAddRouteControllerModule',
	'schedulerUpdateRouteControllerModule',

	'httpInterceptorModule',


	'companyControllerModule',
	'companyListControllerModule',
	'companyHttpServiceModule',
	'companyAddControllerModule',

	'HRControllerModule',
	'companyDetailControllerModule',
	'companySchedulerControllerModule',

	'passengerReportDataControllerModule',
	'passengerReportRouteControllerModule',
	'passengerReportStationControllerModule',
	'passengerReportPassengersControllerModule',
	'passengerReportArrivalControllerModule',

	'companyAdminControllerModule'
	
])