'use strict'
angular.module('injectModules',[
	'ui.router',
	'ui.sortable',
	'ui.bootstrap',
	'ui.calendar',
	'ngAnimate',
	'ngResource',
	'headerModule',
	'leftNavModule',
	'constModule',
	'utilFactoryModule',
	'md5ServiceModule',
	'smsCodeModule',
	'breadcrumbModule',
	'checkControllerModule',
	'gobackModule',
	'tableComponentModule',
	'paginationModule',
	//'sortableDirectiveModule',
	'getRefreshTokenFacotryModule',
	'formValidateSerivceModule',
	'localStorageFactoryModule',
	'loginHttpServiceModule',
	'loginControllerModule',
	'forgetControllerModule',
	
	'activeControllerModule',
	'adminControllerModule',
	
	'passengerControllerModule',
	'passengerHttpServiceModule',
	'passengerAddControllerModule',
	'passengerDetailControllerModule',
	'listControllerModule',
	'reportControllerModule',
	'feedbackControllerModule',
	
	'schedulerControllerModule',
	'schedulerHttpServiceModule',
	'schedulerDriverControllerModule',
	'schedulerDriverDetailControllerModule',
	'schedulerAddDriverControllerModule',
	'schedulerCalendarControllerModule',
	'schedulerAddScheduleControllerModule',
	'schedulerBusControllerModule',
	'schedulerSiteControllerModule',
	'schedulerUpdateSiteControllerModule',
	'schedulerbusCompanyControllerModule',
	
	'schedulerAddBusControllerModule',
	'schedulerBusDetailControllerModule',
	
	'schedulerAddSiteControllerModule',
	
	'schedulerRouteControllerModule',
	'schedulerAddRouteControllerModule',
	'schedulerUpdateRouteControllerModule',

	'httpInterceptorModule'
])