'use strict';

angular.module('app',['injectModules'])
.config(['$stateProvider', '$urlRouterProvider','$qProvider','$httpProvider',function ($stateProvider,$urlRouterProvider,$qProvider,$httpProvider) {

	//$qProvider.errorOnUnhandledRejections(false);

	$httpProvider.interceptors.push('httpInterceptor');
	
	$stateProvider
	.state('entry',{
		url:"/entry",
		templateUrl:"modules/login/entry.html"
	})
	.state('entry.check',{
		url:"/check",
		templateUrl:"modules/login/check.html",
		controller:"checkController"
	})
	.state('entry.login',{
		url:"/login",
		params:{'phoneNumber':null,'requestType':null,'smsCode':null},
		templateUrl:"modules/login/login.html",
		controller:'loginController'
	})
	.state('entry.active',{
		url:"/active",
		params:{'phoneNumber':null,'smsCode':null,'requestType':null},
		templateUrl:"modules/login/active.html",
		controller:'activeController'
	})
	.state('entry.forget',{
		url:'/forget',
		templateUrl:"modules/login/forget.html",
		params:{'phoneNumber':null,'smsCode':null,'requestType':null},
		controller:'forgetController'
	})
	.state('passenger',{
		url:"/passenger",
		templateUrl:'modules/passengerMgmt/passenger.html',
		controller:'passengerController'
	})
	.state('passenger.list',{
		url:'/list',
		templateUrl:'modules/passengerMgmt/list.html',
		controller:'listController'
	})
	.state('passenger.feedback',{
		url:'/feedback',
		templateUrl:'modules/passengerMgmt/feedback.html',
		controller:'feedbackController'
	})
	.state('passenger.report',{
		url:'/report',
		templateUrl:'modules/passengerMgmt/report.html',
		controller:'reportController'
	})
	.state('passenger.detail',{
		url:'/detail',
		params:{
			'status':null,
			'passengerUuid':null,
			'roleType':null,
			'hrUuid':null,
			'secondCompanyId':null,
			'accountId':null,
			'routeName':null,
			'stationName':null,
			'phoneNumber':null,
			'employeeId':null,
			'passengerName':null
		},
		templateUrl:'modules/passengerMgmt/passenger.detail.html',
		controller:'detailController'
	})
	.state('scheduler',{
		url:"/scheduler",
		templateUrl:'modules/schedulerMgmt/scheduler.html',
		controller:'schedulerController'
	})
	.state('scheduler.route',{
		url:'/route',
		templateUrl:'modules/schedulerMgmt/route.html',
		controller:'routeController'
	})
	.state('scheduler.site',{
		url:'/site',
		templateUrl:'modules/schedulerMgmt/site.html',
		controller:'siteController'
	})
	.state('scheduler.dirver',{
		url:'/dirver',
		templateUrl:'modules/schedulerMgmt/dirver.html',
		controller:'dirverController'
	})
	.state('scheduler.bus',{
		url:'/bus',
		templateUrl:'modules/schedulerMgmt/bus.html',
		controller:'busController'
	})
	.state('scheduler.schedule',{
		url:'/schedule',
		templateUrl:'modules/schedulerMgmt/schedule.html',
		controller:'scheduleController'
	})
	$urlRouterProvider.otherwise('entry/check')

}]);